[package]
name = "tiling"
version = "0.1.0"
edition = "2024"

[dependencies]
image.workspace = true
anyhow.workspace = true
reqwest = { workspace = true, features = ["blocking"], optional = true }
copernicus-core = { workspace = true, optional = true }
convection_types.workspace = true

[features]
default-features = ["osm", "copernicus"]
osm = ["dep:reqwest"]
copernicus = ["dep:copernicus-core"]
